keys:
  - &tencent age15sthh2kl3jkpltaq9kuufstjfkcxhh3de0v4nr2qrav4z8676qzq5tlr0n
  - &aiagent age187lfdh66jx5fgu2hcvz58jmjf8j8lzyysxrhz3zx4j0hly9w8p2qlfx8h3
creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *tencent
          - *aiagent
